/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package terrydu.consistent.hashing;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAStart() {
        try {
            App.class.getMethod("start");
        } catch (NoSuchMethodException  e) {
            fail("app should have a start method");
        }
    }
}
